# Generated by Django 2.2.5 on 2019-09-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day2',
            field=models.CharField(blank=True, choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], help_text='星期幾', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='day2_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='day2_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
